### ISSUE TITLE
Computing wasserstein distance between persistence diagrams

### ISSUE THREAD

**Issue by patrycjalucja** [scikit-tda/persim#16]
Hello,
I want to use your library but I got stuck. I would apperciate your help with my issue very much.
I'm trying to compute Wasserstein distance between two persistence diagrams generated through Python Ripser library. I found two interesting functions in Persim: sliced_wasserstein and wasserstein_matching.

My diagram generation looks like that:

    data = json.loads(data)
    data = pd.DataFrame.from_dict(data)
    rips = Rips()
    dgms = rips.fit_transform(data)
    for i in dgms:
        print(type(i))
        i.tofile(directory+"diagram.txt")
    plot_diagrams(dgms, show=False)
    plt.savefig("persistence_diagram.png")
    plt.close()
'dgms' is a list which contains numpy arrays, so I'm getting them out in my 'for' line.

My Wasserstein function usage looks like that:

    with open(loc) as f:
        img1 = np.fromfile(f)
        f.close()
    with open(loc2) as f:
        img2 = np.fromfile(f)
        f.close()
    persim.sliced_wasserstein(img1, img2)

I tried to pass to wasserstein_matching three kinds of data (diagram in .png, dgms list and np.array) but all I constantly get is an error 'IndexError: too many indices for array'. So I switched into sliced_wasserstein where I get such error:
``
Traceback (most recent call last):
  File "C:/Users/Patka/PycharmProjects/MGR/Mapper.py", line 26, in <module>
    persim.sliced_wasserstein(img1, img2)
  File "C:\Users\Patka\environmentpython\lib\site-packages\persim\sliced_wasserstein.py", line 53, in sliced_wasserstein
    sw += step * cityblock(sorted(V1), sorted(V2))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
One weird thing for me is that when I print i.shape before saving to file, I get two dimensions, e.g. (12,2) but when I read from the same file using numpy.fromfile() I get a tuple (12,).
``

Does anybody have a cure for that? My final aim is to compute distances for lots of diagrams and to cluster them but I'm stuck on comparing two ones...

**Comment by sauln** [comment]
Hi, you might be getting confused with what the `wasserstein_matching` does.  All that `bottleneck_matching` and `wasserstein_matching` do is visualizing the matching that created the distance. Unfortunately, we don't at this time have a wasserstein distance that is license compatible with the project. 

If you wanted to visualize some matchings, I would look at `bottleneck` and `bottleneck_matching` functions to see what happens. 

An image will not work, it would be best to feed the diagrams directly from the output of ripser.py. You can save with np.save rather than saving the figure.
