### ISSUE TITLE
Bottleneck distance between identical diagrams is non-zero. 

### ISSUE THREAD

**Issue by MelissaMcguirl** [scikit-tda/persim#19]
bottleneck function repeatedly outputs non-zero distance between identical persistence diagram inputs. For example:

>>> data = np.random.random((5,2))
>>> pd = rips.fit_transform(data)
>>> d = bottleneck(pd[0], pd[0])
>>> d
0.05305507779121399
>>>

Note, at first pass it seems like d gets smaller as the number of points in data increases?

**Comment by ctralie** [comment]
Hello Melissa, thank you so much for bringing this to our attention.  I will have a look at this as soon as I can.  Sorry for the trouble!

**Comment by ctralie** [comment]
Okay, finally getting back to this.  I'm running the following code here

```python
    from ripser import ripser
    from persim import bottleneck, bottleneck_matching
    import matplotlib.pyplot as plt
    import numpy as np
    np.random.seed(5) #3
    data = np.random.randn(5, 4)
    pd = ripser(data)['dgms'][0]
    dist, (matchidx, D) = bottleneck(pd, pd, matching=True)
    print(dist)
    bottleneck_matching(pd, pd, matchidx, D)
    plt.show()
```

Visually, the bug is apparent.

### ![image](https://user-images.githubusercontent.com/1270246/64065560-04305c80-cbdd-11e9-847a-eee0e0c30bfa.png)

A very small error is made

![image](https://user-images.githubusercontent.com/1270246/64065570-18745980-cbdd-11e9-8b82-a76cf33fdea4.png)


I'll try to see if I can figure out why...
