### ISSUE TITLE
Persistence Landscape 

### ISSUE THREAD

**Issue by maxsw2** [scikit-tda/persim#62]
During the calculation of landscapes, how is the number of layers/lambdas decided?

**Comment by catanzaromj** [comment]
@maxsw2 The number of layers is determined by the overlaps of the bars in the barcode (equivalently, in how the points in the persistence diagram are 'nested'). See Figures 2 and 3 in the original paper by Bubenik [here](https://www.jmlr.org/papers/volume16/bubenik15a/bubenik15a.pdf). In particular, if none of the bars overlap at all, there will only be a single layer. The maximum number of layers possible is given by the number of bars in the barcode.

In terms of the code, we compute all possible layers with the `compute_landscape` methods. For `PersLandscapeApprox`, the attribute `values` encodes a list, indexed on the layers/lambdas, so that `values[i]` is a sampling of the `i`th layer. The same is true for `PersLandscapeExact` and its `critical_pairs` attribute.
