### ISSUE TITLE
Persistence Landscapes and Machine Learning notebook issue

### ISSUE THREAD

**Issue by Renaud38** [scikit-tda/persim#77]
Hi, 

I would like to use this notebook and it used to be visible but there seem to be an issue with it now.

Is it possible to fix it?

Thanks,
Renaud

**Comment by catanzaromj** [comment]
@Renaud38 Sorry about that. This should be fixed in persim v0.3.5. Please take a look at the actual notebook [here](https://github.com/scikit-tda/persim/blob/master/docs/notebooks/Persistence%20Landscapes%20and%20Machine%20Learning.ipynb) and its rendering in the docs [here](https://persim.scikit-tda.org/en/latest/notebooks/Persistence%20Landscapes%20and%20Machine%20Learning.html).

Thanks for brining this to our attention!
